version: "3.8"

services:
  server:
    build:
      context: ../server
      dockerfile: ../docker/Dockerfile.server
    ports:
      - "3000:3000"
    depends_on:
      - mongodb
  clientv1:
    build:
      context: ../clientv1
      dockerfile: ../docker/Dockerfile.client
    ports:
      - "2173:5173"
    command: -tail -f /dev/null
  mongodb:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data:
